### PR TITLE
Use composer and add unit tests

### PR DESCRIPTION
**Pull request by euantorano**
This patch set updates the API client significantly to make it
installable via Composer.

It also adds some very basic unit tests (more to be added at a later
date), and moves classes over to proper namespaces as well as including
proper exceptions.

Additionally, it includes a couple of very basic examples.

### CODE REVIEW

**Comment by euantorano** [comment]
In addition to this patchiest (should it be merged), the library should be published on [packagist](https://packagist.org), and [Travis CI](https://travis-ci.org) should be used to run Continuous Integration in order to run the unit tests.

**Comment by sharpless512** [comment]
Wow great! I will take a look at it on Monday. Awesome work!

**Comment by sharpless512** [comment]
https://packagist.org/packages/igdb/api

**Comment by euantorano** [comment]
Great, that should make life a lot easier for people!

**Pull request merged**
